# -*- coding: utf-8 -*-
"""Generate the final Al-Meezan restoration report.

Reads everything from the DB (laws_v2, articles_v2, attachments_v2,
verification_log_v2) and produces a comprehensive markdown report
listing every (re)ingested law with name/number/year + verification
status.

Output: data/meezan_enum/RESTORATION_REPORT.md
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
OUT_FP = ROOT / "data" / "meezan_enum" / "RESTORATION_REPORT.md"


def _pg_query(sql: str) -> list[tuple]:
    cmd = [
        "docker", "exec", "-i", "legal_db",
        "psql", "-U", "raguser", "-d", "ragdb",
        "-t", "-A", "-F", chr(31),
    ]
    r = subprocess.run(
        cmd, input=sql, capture_output=True, text=True,
        check=False, timeout=60, encoding="utf-8",
    )
    if r.returncode != 0:
        raise RuntimeError(r.stderr[:400])
    rows = []
    for line in r.stdout.strip().split("\n"):
        if not line:
            continue
        rows.append(tuple(line.split(chr(31))))
    return rows


def main() -> int:
    lines: list[str] = []
    lines.append("# Al-Meezan Legal Corpus Restoration — Final Report")
    lines.append("")
    lines.append("Generated by `scripts/meezan_report.py`.")
    lines.append("")

    # ── Summary counts ────────────────────────────────────────
    c_laws = int(_pg_query("SELECT COUNT(*) FROM laws_v2;")[0][0])
    c_arts = int(_pg_query("SELECT COUNT(*) FROM articles_v2;")[0][0])
    c_atts = int(_pg_query("SELECT COUNT(*) FROM attachments_v2;")[0][0])
    c_rels = int(_pg_query("SELECT COUNT(*) FROM law_relationships_v2;")[0][0])
    c_subs = int(_pg_query("SELECT COUNT(*) FROM subjects_v2;")[0][0])

    lines.append("## 📊 Overall Corpus")
    lines.append("")
    lines.append(f"| Table | Rows |")
    lines.append(f"|---|---:|")
    lines.append(f"| laws_v2              | {c_laws:,} |")
    lines.append(f"| articles_v2          | {c_arts:,} |")
    lines.append(f"| attachments_v2       | {c_atts:,} |")
    lines.append(f"| law_relationships_v2 | {c_rels:,} |")
    lines.append(f"| subjects_v2          | {c_subs:,} |")
    lines.append("")

    # ── Status breakdown ───────────────────────────────────────
    rows = _pg_query("SELECT status, COUNT(*) FROM laws_v2 GROUP BY status ORDER BY 2 DESC;")
    lines.append("## 🔖 By Status")
    lines.append("")
    lines.append("| Status | Count |")
    lines.append("|---|---:|")
    for st, cnt in rows:
        lines.append(f"| {st} | {cnt} |")
    lines.append("")

    # ── Domain breakdown ───────────────────────────────────────
    rows = _pg_query(
        "SELECT COALESCE(legal_domain,'(unset)'), COUNT(*) "
        "FROM laws_v2 GROUP BY legal_domain ORDER BY 2 DESC;"
    )
    lines.append("## 🏛️ By Legal Domain")
    lines.append("")
    lines.append("| Domain | Count |")
    lines.append("|---|---:|")
    for dom, cnt in rows:
        lines.append(f"| {dom} | {cnt} |")
    lines.append("")

    # ── Year breakdown (recent 10) ────────────────────────────
    rows = _pg_query(
        "SELECT law_year, COUNT(*) FROM laws_v2 "
        "WHERE law_year IS NOT NULL "
        "GROUP BY law_year ORDER BY law_year DESC LIMIT 15;"
    )
    lines.append("## 📅 Recent Years")
    lines.append("")
    lines.append("| Year | Laws |")
    lines.append("|---|---:|")
    for yr, cnt in rows:
        lines.append(f"| {yr} | {cnt} |")
    lines.append("")

    # ── Verification summary ──────────────────────────────────
    try:
        rows = _pg_query(
            "SELECT status, COUNT(*) FROM verification_log_v2 "
            "GROUP BY status ORDER BY 2 DESC;"
        )
        if rows:
            lines.append("## ✅ Verification Log (latest runs)")
            lines.append("")
            lines.append("| Status | Count |")
            lines.append("|---|---:|")
            for st, cnt in rows:
                lines.append(f"| {st} | {cnt} |")
            lines.append("")
    except Exception:
        pass

    # ── Full list of laws (by year desc, then number) ────────
    lines.append("## 📜 Full Law List")
    lines.append("")
    lines.append("| # | Al-Meezan ID | Type | Number | Year | Status | Articles | Attachments | Title |")
    lines.append("|---|---:|---|---:|---:|---|---:|---:|---|")
    rows = _pg_query(
        """
        SELECT l.almeezan_id,
               COALESCE(l.law_type, '—'),
               COALESCE(l.law_number, '—'),
               COALESCE(l.law_year::text, '—'),
               l.status,
               (SELECT COUNT(*) FROM articles_v2 WHERE law_id=l.id),
               (SELECT COUNT(*) FROM attachments_v2 WHERE law_id=l.id),
               COALESCE(l.law_name, '—')
        FROM laws_v2 l
        ORDER BY l.law_year DESC NULLS LAST, l.law_number::int DESC NULLS LAST
        LIMIT 5000;
        """
    )
    for i, r in enumerate(rows, 1):
        mid, ltype, num, yr, status, narts, natts, title = r
        title = title.replace("|", "/").strip()
        if len(title) > 120:
            title = title[:117] + "..."
        lines.append(
            f"| {i} | {mid} | {ltype} | {num} | {yr} | {status} | "
            f"{narts} | {natts} | {title} |"
        )

    OUT_FP.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT_FP}")
    print(f"  total laws listed: {len(rows):,}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
